import fs from "fs";
import path from "path";
import crypto from "crypto";
import {transactionsStatusNumberToName,type GenLayerClient} from "genlayer-js/types";
const ROOT=process.cwd();const sleep=(ms:number)=>new Promise(r=>setTimeout(r,ms));
const sha256=(p:string)=>crypto.createHash("sha256").update(fs.readFileSync(p)).digest("hex");
async function waitFinal(client:any,txId:`0x${string}`,label:string){for(let i=0;i<240;i++){const tx:any=await client.getTransaction({hash:txId});const raw=tx?.statusName??tx?.status_name??tx?.status??"";const name=String((transactionsStatusNumberToName as Record<string,string>)[String(raw)]||raw).toUpperCase();process.stdout.write(`\r${label}: ${name||"PENDING"}        `);if(name.includes("FINALIZED")){process.stdout.write("\n");return tx}if(name.includes("UNDETERMINED"))throw new Error(`${label} became UNDETERMINED`);if(name.includes("REVERT")||name.includes("CANCEL")||name.includes("FAIL"))throw new Error(`${label} failed with ${name}`);if(name.includes("READY_TO_FINALIZE")){try{await client.finalizeTransaction({txId})}catch{}}await sleep(5000)}throw new Error(`${label} did not finalize within the deployment window`)}
async function deployOne(client:any,file:string,args:any[],label:string){const filePath=path.join(ROOT,"contracts",file);const code=new Uint8Array(fs.readFileSync(filePath));const txId=await client.deployContract({code,args}) as `0x${string}`;await waitFinal(client,txId,label);const tx:any=await client.getTransaction({hash:txId});const address=tx?.txDataDecoded?.contractAddress||tx?.data?.contract_address||tx?.contractAddress;if(!address)throw new Error(`${label}: finalized but contract address could not be decoded`);return{txId,address:String(address),sourceSha256:sha256(filePath)}}
async function finalizedWrite(client:any,address:string,functionName:string,args:any[],label:string){const draft={address:address as `0x${string}`,functionName,args,value:0n};let fees:any;try{const e=await client.estimateTransactionFeesForWrite(draft);fees=e?.distribution&&e?.feeValue!==undefined?{distribution:e.distribution,feeValue:e.feeValue}:undefined}catch{}const txId=await client.writeContract({...draft,...(fees?{fees}:{})}) as `0x${string}`;await waitFinal(client,txId,label);return txId}
export default async function main(client:GenLayerClient<any>){const chainId=Number((client as any)?.chain?.id);if(chainId!==61999)throw new Error(`Frelease deploy aborted: expected Studionet 61999, connected chain is ${chainId||"unknown"}`);await (client as any).initializeConsensusSmartContract();console.log("Frelease deployment target: GenLayer Studionet 61999");const registry=await deployOne(client,"frelease_registry.py",[],"FreleaseRegistry");const evaluator=await deployOne(client,"frelease_evaluator.py",[registry.address],"FreleaseEvaluator");const configureEvaluatorTx=await finalizedWrite(client,registry.address,"set_evaluator_once",[evaluator.address],"Configure Registry → Evaluator");const manifest={project:"Frelease",network:"GenLayer Studionet",chainId:61999,rpc:"https://studio.genlayer.com/api",explorer:"https://explorer-studio.genlayer.com",deployedAt:new Date().toISOString(),contracts:{freleaseRegistry:{address:registry.address,deployTx:registry.txId,configureEvaluatorTx,sourceSha256:registry.sourceSha256},freleaseEvaluator:{address:evaluator.address,deployTx:evaluator.txId,sourceSha256:evaluator.sourceSha256}}};fs.mkdirSync(path.join(ROOT,"deployments"),{recursive:true});fs.writeFileSync(path.join(ROOT,"deployments","studionet.json"),JSON.stringify(manifest,null,2)+"\n");console.log("\nCanonical Studionet deployment:\n"+JSON.stringify(manifest,null,2));console.log(`\nNEXT_PUBLIC_FRELEASE_REGISTRY_ADDRESS=${registry.address}`);console.log(`NEXT_PUBLIC_FRELEASE_EVALUATOR_ADDRESS=${evaluator.address}`)}
